n = 8;
m = 9;
A = randn(n, m);
nset = dec2bin(0:(2^(n) - 1));
mset = dec2bin(0:(2^(m) - 1));
original = 0;
for i = 1:size(nset, 1)
  for j = 1:size(mset, 1)
    v = logical(nset(i, :) - '0');
    h = logical(mset(j, :) - '0');
    original = original + (v * A * h') ^ 5;
  end
end

optimized = 2^(n+m)*(((sum(sum((repmat(( sum(A, 1) .* sum(A, 1)), [n, 1])  .* ( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A)), 2), 1)  .* -40)  ...
              + (sum((( sum(A, 1) .* sum(A, 1))  .* sum((repmat(sum(A, 1), [n, 1])  .* ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1]))), 1)), 2)  .* -10) ... 
              + (( sum(sum(A, 2), 1) .* sum(( ( sum(A, 2) .* sum(A, 2)) .* sum(( A .* A), 2)), 1))  .* -60) ...
              + (sum((repmat(sum(sum(A, 2), 1), [n, 1])  .* (repmat(sum(sum(A, 2), 1), [n, 1])  .* sum(( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A), 2))), 1)  .* 60) ...
              + (sum((sum(( A .* repmat(sum(A, 1), [n, 1])), 2)  .* sum((repmat(sum(A, 1), [n, 1])  .* ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1]))), 2)), 1)  .* 60) ...
              + (sum(sum(( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* ( A .* ( A .* A))), 2), 1)  .* 80) ... 
              + (sum((sum(A, 2)  .* (sum(A, 2)  .* sum(( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A), 2))), 1)  .* -40) ...
              + (sum((repmat(sum(( sum(A, 2) .* sum(A, 2)), 1), [n, 1])  .* sum(( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A), 2)), 1)  .* 60) ...
              + ( ( ( sum(A, 1) * (A')) * ( ( A * (A')) * sum(A, 2))) .* 120) ...
              + (sum((( sum(A, 2) .* sum(A, 2))  .* sum((repmat(sum(A, 2), [1, m])  .* ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1]))), 2)), 1)  .* -10) ...
              + (( sum(sum(A, 2), 1) .* sum(( ( sum(A, 1) .* sum(A, 1)) .* sum(( A .* A), 1)), 2))  .* -60) ...
              + (sum((sum(repmat(( sum(A, 2) .* sum(A, 2)), [1, m]), 1)  .* sum((repmat(sum(A, 2), [1, m])  .* ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1]))), 1)), 2)  .* 15) ...
              + ( ( ( sum(sum(A, 2), 1) * (sum(A, 2)')) * ( ( A * (A')) * sum(A, 2))) .* 60) ...
              + ( ( ( sum(sum(A, 2), 1) * ( sum(A, 1) * (A'))) * ( A * (sum(A, 1)'))) .* 60) ...
              + ((sum(sum(A, 2), 1)  .* ( sum(( sum(A, 1) .* sum(A, 1)), 2) .* sum(( sum(A, 1) .* sum(A, 1)), 2)))  .* 15) ...
              + ((sum(sum(A, 2), 1)  .* (( sum(sum(A, 2), 1) .* sum(sum(A, 2), 1))  .* ( sum(sum(A, 2), 1) .* sum(sum(A, 2), 1))))  .* 1) ...
              + ((sum(( sum(A, 1) .* sum(A, 1)), 2)  .* ( sum(sum(A, 2), 1) .* ( sum(sum(A, 2), 1) .* sum(sum(A, 2), 1))))  .* 10) ...
              + (sum((sum(( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A), 2)  .* repmat(sum(sum(( A .* A), 2), 1), [n, 1])), 1)  .* 60) ...
              + ((sum(( sum(A, 2) .* sum(A, 2)), 1)  .* ( sum(sum(A, 2), 1) .* ( sum(sum(A, 2), 1) .* sum(sum(A, 2), 1))))  .* 10) ...
              + ((sum(sum(( A .* A), 2), 1)  .* ( sum(sum(A, 2), 1) .* ( sum(sum(A, 2), 1) .* sum(sum(A, 2), 1))))  .* 10) ...
              + (sum((sum(repmat(( sum(A, 1) .* sum(A, 1)), [n, 1]), 2)  .* sum((repmat(sum(A, 2), [1, m])  .* ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1]))), 2)), 1)  .* 30) ...
              + (sum(sum((( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A)  .* repmat(sum(( A .* A), 1), [n, 1])), 2), 1)  .* -120) ...
              + ((sum(sum(A, 2), 1)  .* ( sum(( sum(A, 1) .* sum(A, 1)), 2) .* sum(sum(( A .* A), 2), 1)))  .* 30) ...
              + (sum(sum((( repmat(sum(A, 2), [1, m]) .* repmat(sum(( A .* A), 1), [n, 1]))  .* repmat(sum(( A .* A), 1), [n, 1])), 2), 1)  .* -30) ...
              + ((sum(sum(A, 2), 1)  .* ( sum(( sum(A, 2) .* sum(A, 2)), 1) .* sum(sum(( A .* A), 2), 1)))  .* 30) ...
              + (sum(( repmat(sum(sum(A, 2), 1), [n, 1]) .* ( sum(( A .* A), 2) .* sum(( A .* A), 2))), 1)  .* -30) ...
              + (sum(( repmat(sum(sum(A, 2), 1), [n, 1]) .* sum(( ( A .* A) .* ( A .* A)), 2)), 1)  .* 20) ...
              + (( sum(sum(A, 2), 1) .* ( sum(sum(( A .* A), 2), 1) .* sum(sum(( A .* A), 2), 1)))  .* 15) ...
              + (sum((sum(( A .* A), 2)  .* sum(( ( repmat(sum(A, 2), [1, m]) .* repmat(sum(A, 1), [n, 1])) .* A), 2)), 1)  .* -120)  + ( sum(( ( ( A * (A')) .* ( A * (A'))) * repmat(sum(sum(A, 2), 1), [n, 1])), 1) .* 30))) / 1024; 
          
normalization = sum(abs(original(:)));
assert(sum(abs(original(:) - optimized(:))) / normalization < 1e-10);
